name: "Workflow needs"

on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Let's go"
        run: echo "J'ai été éxecuté !!"
  second_job:
    needs: 
      - first_job
    runs-on: ubuntu-latest
    steps:
      - name: "Second job"
        run: "Le job FIRST_JOB a été exécuté ! oO"